# Generated by Django 3.2.3 on 2021-06-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.TextField()),
                ('date', models.DateField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pepsi.business')),
            ],
        ),
    ]
