# Generated by Django 3.2.3 on 2021-06-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepsi', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='comments',
        ),
    ]
