# Generated by Django 3.2.3 on 2021-06-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepsi', '0003_rename_name_booking_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
