# Generated by Django 3.2.3 on 2021-06-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepsi', '0004_alter_booking_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created',
            new_name='createdDate',
        ),
    ]
