# Generated by Django 3.2.3 on 2021-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepsi', '0006_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('AC', 'Accepted'), ('DN', 'Denied')], default='PN', max_length=2),
        ),
    ]
