# Generated by Django 3.2.3 on 2021-06-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepsi', '0007_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pepsi.business'),
        ),
    ]
