# Generated by Django 3.2.7 on 2021-11-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepsi', '0011_auto_20211104_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='post',
            new_name='booking',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
